---
apiVersion: v1
kind: Namespace
metadata:
  name: mock-storage-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-storage-operator-controller-manager
  namespace: mock-storage-operator-system
  labels:
    app: mock-storage-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-storage-operator
  template:
    metadata:
      labels:
        app: mock-storage-operator
    spec:
      serviceAccountName: mock-storage-operator-controller-manager
      containers:
        - name: manager
          image: localhost/mock-storage-operator:latest
          imagePullPolicy: IfNotPresent
          command: [/manager]
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8080
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
